### ISSUE TITLE
Cannot read property 'count' of undefined

### ISSUE THREAD

**Issue by FLYBYME** [moudy/agenda-ui#18]
```
TypeError: Cannot read property 'count' of undefined
    at Store.count (/home/bob/files/node_modules/agenda-ui/lib/store.js:41:37)
    at Store.definitions (/home/bob/files/node_modules/agenda-ui/lib/store.js:69:26)
    at /home/bob/files/node_modules/agenda-ui/lib/api.js:13:11
    at Layer.handle [as handle_request] (/home/bob/files/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/bob/files/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/home/bob/files/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/bob/files/node_modules/express/lib/router/layer.js:95:5)
    at /home/bob/files/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/home/bob/files/node_modules/express/lib/router/index.js:330:12)
    at next (/home/bob/files/node_modules/express/lib/router/index.js:271:10)
    at Function.handle (/home/bob/files/node_modules/express/lib/router/index.js:176:3)
    at router (/home/bob/files/node_modules/express/lib/router/index.js:46:12)
    at Layer.handle [as handle_request] (/home/bob/files/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/bob/files/node_modules/express/lib/router/index.js:312:13)
    at /home/bob/files/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/bob/files/node_modules/express/lib/router/index.js:330:12)

``

**Comment by wesley-harding** [comment]
My guess is this is related to a (poor) choice to change the DB driver in agenda. Seems like it might be a bit painful to fix.

https://github.com/rschmukler/agenda/issues/213

**Comment by FLYBYME** [comment]
Do you have advice on what version of agenda should be used?

**Comment by wesley-harding** [comment]
You should be good with 0.6.8.  You'll also need to use an older version of
Mongo or mongoose (I can't remember which one off the top of my head)

**Comment by Lighiche** [comment]
Also having this issue

**Comment by jdnichollsc** [comment]
+1

**Comment by jdnichollsc** [comment]
See more info please:

http://screencast.com/t/TgcnNQvu8D
http://screencast.com/t/LhV6JnZnm

**Comment by harelba** [comment]
I have the same issue, and downgrading agenda to the older version doesn't work as well.

**Comment by pavan612** [comment]
agenda._db = agenda._collection; //add this line before passing agenda to agenda-ui
app.use('/agenda/admin/jobs', agendaUI(agenda, {poll: 30000}));

**Comment by harelba** [comment]
@pavan612 thanks for trying to help. Tried it, but I'm still getting the error - 

````
TypeError: Cannot read property 'count' of undefined
    at Store.count (/Users/harel/dev/trickly/src/trickly/node_modules/agenda-ui/lib/store.js:41:37)
    at Store.definitions (/Users/harel/dev/trickly/src/trickly/node_modules/agenda-ui/lib/store.js:69:26)
````

Agenda version 0.73
Agenda-ui version 0.0.7

**Comment by pavan612** [comment]
@harelba this is my working code
[changes.txt](https://github.com/moudy/agenda-ui/files/50807/changes.txt)

**Comment by jeonghwan-kim** [comment]
+1

**Comment by jeonghwan-kim** [comment]
```
var express = require('express');
var http = require('http');
var Agenda = require('agenda');
var agendaUI = require('agenda-ui');

var app = express();
var agenda = new Agenda({
  db: {
    address: 'localhost:27017/agenda-sample'
  }
}, function (err) {
  if (err) throw err;

  console.log('Connected to database');

  // Should add this code before setting middleware.
  agenda._db = agenda._collection;

  app.use('/agenda-ui', agendaUI(agenda, {poll: 1000}));

  http.createServer(app).listen(9000, function () {
    console.log('Express listeing on 9000 port');
  });

});
```

**Comment by brebaje** [comment]
Thanks @pavan612 that hack worked :)

**Comment by geototti21** [comment]
I get the same error witj @FLYBYME , I tried the solution suggested from @pavan612 but it didnt work. I'm using the latest versions from both agenda and agenda-ui. Any help? Does anyone make it work with the latest versions?
Thanks

**Comment by pavan612** [comment]
Hi can you post sample code of your problem

**Comment by geototti21** [comment]
@pavan612  my code:

```javascript
var agenda = new Agenda({db: {address: configDB.url, collection: "agendaJobs"}});

agenda.name(os.hostname() + '-' + process.pid); 

agenda.on('ready', function() {
  agenda.every('30 seconds', 'Say the time', {time: new Date()});
  agenda._db = agenda._collection;
  agenda.start();
});

//some session stuff there

app.use('/agenda-ui', agendaUI(agenda, {poll: 1000}));

//...
```

When I go to the the node terminal I have the same error with @FLYBYME and on the browser console the following:

![error](https://cloud.githubusercontent.com/assets/4247555/12577002/97c6aa8c-c40f-11e5-8662-5cb3839ca0e0.png)

**Comment by flashsnake-so** [comment]
Thanks @pavan612 that hack worked 2 :)

**Comment by coderfox** [comment]
same as @geototti21 .
I doubt that the problem may relate to that the Agenda-UI is initializied before agenda connected to the database. I would like to know if it is possible to let Agenda-UI connect to the database on its own.

**Comment by LeandroFavero** [comment]
For me the hacks doesn't works :-(

**Comment by weareu** [comment]
So to get the hack to work and only init ui after agenda has connected to mongo I did this:
var agenda = new Agenda({db: { address: config.agendaDb } }, function() {
	// Should add this code before setting middleware.
	agenda._db = agenda._collection;
	console.log('Setup Middleware for Agenda');	
	app.use('/agendaui/', agendaUI(agenda, {poll: 1000}));
});

**Comment by vsmori** [comment]
Tried all solutions, none worked :-1:

**Comment by lusa** [comment]
I got Agendash working very quickly with no issues so far. https://github.com/joeframbach/agendash
